apiVersion: v1
kind: Secret
metadata:
  name: acme-dns-secret
  namespace: cert-manager
stringData:
  acmedns.json: |
    {
        "k3s.demothings.ru": {
            "username": "${ACME_USERNAME}",
            "password": "${ACME_PASSWORD}",
            "fulldomain": "${ACME_FULLDOMAIN}",
            "subdomain": "${ACME_SUBDOMAIN}",
            "allowfrom": []
        },
        "argocd.k3s.demothings.ru": {
            "username": "${ACME_USERNAME_ROOT}",
            "password": "${ACME_PASSWORD_ROOT}",
            "fulldomain": "${ACME_FULLDOMAIN_ROOT}",
            "subdomain": "${ACME_SUBDOMAIN_ROOT}",
            "allowfrom": []
        }
    }
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-k3s
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tools.nere@ya.ru
    privateKeySecretRef:
      name: letsencrypt-acme-issuer-account-key
    solvers:
    - dns01:
        acmeDNS:
          host: https://auth.acme-dns.io
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true