apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: argo-cd
  name: argo-cd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 8.6.1
  targetNamespace: argo-cd
  valuesContent: |-
    crds:
      keep: false
    
    global:
      logging:
        format: json
        level: info
      domain: "argocd.k3s.local"
    
    configs:
      params:
        server.insecure: true
      
      repositories: {}
        # istio-helm-repo:
        #   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
        #   name: istio.io
        #   type: helm

      secret:
        # -- Bcrypt hashed admin password
        ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
        ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
        argocdServerAdminPassword: "$2a$10$lkiWzwDrUE/xtMYe1fFmTuxmeLjipdNG6Nu44DQO0chLnxGn3rVzq"
      
    server:
      name: server
      replicas: 1
      metrics:
        enabled: true
      
      ingress:
        enabled: true
        hostname: "argocd.k3s.local"
        annotations: {}
        ingressClassName: traefik
        path: /
        pathType: Prefix
        tls: false
